# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'LOARANG-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod "RxGesture"
pod 'RxDataSources'

pod 'SnapKit', '~> 5.0.0'

pod 'SwiftyJSON'

pod 'SwiftSoup'

pod 'RealmSwift'

pod 'FirebaseAnalytics'
  # Pods for LOARANG-MVVM

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end

end
